# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 29fcf03b158126ca7d751c7b19bc720bdad559c783d77183bc4b36b7a2d8306cf9515140a00d7fb6ddc204238b57b43ca3368d337e09543aaa751c29eaff7b72

test:
  secret_key_base: 7bdd590fbbf6ee24b9bceee8dcce77c3ca7b94d94ef9017206f0410630e0ed674914b6f2126a12b694f3acc17646fa5827cebd9d167e73d4c15f8266a461d679

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
